physical-parameters:
  # Domain parameters
  Lx: 80e3        # (m)
  Ly: 80e3        # (m)
  nx: 20         # number of elements in the x-direction
  ny: 20         # number of elements in the y-direction

  
modeling-parameters:
  # Model parameters
  T: 255.0                # (K) temperature
  a_in: 1.7               # accumulation rate at the inflow
  da:   -2.7              # change of accumulation rate
  a_in_p: 1.87            # nurged accumulation rate at the inflow
  da_p: -2.835            # nurged change of accumulation rate
  num_years: 60          # number of years to run the model
  timesteps_per_year: 2   # number of timesteps per year

  example_name: "ISMIP"  # these can be found in the examples folder
  ParamFile: "IsmipA.par"
  verbose: False            # verbosity level

enkf-parameters:
  # Ensemble Kalman Filter parameters
  Nens: 16                      # number of ensemble members (now set in the command line)
  freq_obs: 3              # frequency of observations
  obs_max_time: 32           # maximum time for observations
  obs_start_time: 2             # start time for observations

  num_state_vars: 3       # number of state variables  [h,u,v]
  num_param_vars: 1       # number of parameter variables [smb]
  vec_inputs: ['h','u','v','smb']
  observed_params: ['smb']

  # Statistical parameters (based on the number of state variables)
  sig_model: [0.1,0.1,0.1] # model error standard deviation
  sig_obs: [5,2,0.5,0.4]   # observation error standard deviation
  sig_Q: [5,2,0.4,0.4]    # process noise standard deviation

  seed: 1                 # seed for random number generator
  inflation_factor: 1.2          # inflation factor
  localization_flag: False      # localization flag: True, False

  # estimation flags
  joint_estimation: True # joint estimation flag: True, False
  parameter_estimation: True # parameter estimation flag: True, False

  # nurged parameters
  h_nurge_ic: 100         # nurged increment for initial thickness
  u_nurge_ic: 0         # nurged increment for initial velocity
  nurged_entries_percentage: 0.10 #%     # percentage of nurged entries in the state vector

  # enkf model parameters
  model_name: "issm"               # name of the model
  model_solver: "solver_weertman"     # name of the solver
  filter_type: "EnKF"               # name of the filter: EnKF, DEnKF, EnTKF, EnRSKF
  local_analysis: False           # local analysis flag: True, False, global analysis is default
  parallel_flag: "MPI_model"             # parallel flag: Serial, MPI, MPI_model
  n_modeltasks: 1                     # number of model tasks (for MPI)
  commandlinerun: "True"              # command line run flag: True, False
  execution_flag: 2                   #`execution flag: 0 ->default, 1 -> sequntial, 2 -> even_distribution_of_problem size, 3 -> even_distribution_of_problem size with load balancing
 
